/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    sites: Site;
    pages: Page;
    media: Media;
    domains: Domain;
    releases: Release;
    facts: Fact;
    crawls: Crawl;
    issues: Issue;
    'audit-log': AuditLog;
    rooms: Room;
    offers: Offer;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    domains: DomainsSelect<false> | DomainsSelect<true>;
    releases: ReleasesSelect<false> | ReleasesSelect<true>;
    facts: FactsSelect<false> | FactsSelect<true>;
    crawls: CrawlsSelect<false> | CrawlsSelect<true>;
    issues: IssuesSelect<false> | IssuesSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr') | ('en' | 'fr')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'fr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      touchPageSeo: TaskTouchPageSeo;
      publishSite: TaskPublishSite;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('super-admin' | 'owner' | 'editor')[];
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug: string;
  plan?: ('concierge' | 'starter' | 'managed' | 'dedicated') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  tenant?: (number | null) | Tenant;
  brandProposal?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  name: string;
  /**
   * Platform-wide unique; the public preview lives at /s/<slug>
   */
  slug: string;
  /**
   * The hotel’s current website, imported into the fact base from the Website panel (Phase 3 ingest).
   */
  sourceUrl?: string | null;
  /**
   * Public name shown on the site. Backfilled from the tenant name by migration.
   */
  brandName?: string | null;
  /**
   * IANA time zone for offers, events and opening hours.
   */
  timezone?: string | null;
  enabledLocales?: ('en' | 'fr' | 'de' | 'es' | 'it')[] | null;
  defaultLocale?: ('en' | 'fr' | 'de' | 'es' | 'it') | null;
  theme?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Maison: Classic and warm: serif headings, cream background, full-width photos. Suits heritage and boutique hotels. · Atelier: Modern and minimal: sans-serif type, white space, square corners, photo beside the headline. Suits design and city hotels. · Soirée: Dark and elegant: night palette, gold accent, centred headlines. Suits luxury and evening-led hotels. · Lumière: Luxurious and bright: ivory pages, a full-screen photo hero with a glass booking bar, navy bands and cards, champagne-gold buttons, large serif headlines. Suits upscale boutique and resort hotels.
   */
  template?: ('maison' | 'atelier' | 'soiree' | 'lumiere') | null;
  /**
   * Template upgrades reach canary sites first (customer zero, our demo sites), then everyone. Render-time only: not part of releases.
   */
  designChannel?: ('stable' | 'canary') | null;
  /**
   * Optional: leave empty to use the template as designed. Colours as #rrggbb. Button text, links and secondary text are adjusted automatically to stay readable (WCAG AA).
   */
  brand?: {
    accent?: string | null;
    background?: string | null;
    text?: string | null;
    /**
     * Empty: the template font
     */
    headingFont?: ('inter' | 'manrope' | 'playfair' | 'cormorant') | null;
    /**
     * Empty: the template font
     */
    bodyFont?: ('inter' | 'manrope' | 'playfair' | 'cormorant') | null;
    /**
     * Empty: the template corners
     */
    corners?: ('square' | 'soft' | 'round') | null;
  };
  status?: ('draft' | 'live' | 'suspended') | null;
  /**
   * Short line under the name, used in the header and search results
   */
  tagline?: string | null;
  /**
   * Logo image URL (https). Remote until the media pipeline exists
   */
  logoUrl?: string | null;
  /**
   * The "Book" button in the header. A page slug (e.g. contact), a URL, tel: or mailto:. No booking logic runs on the platform
   */
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Set by the release pipeline. Rollback moves this pointer.
   */
  currentRelease?: (number | null) | Release;
  /**
   * Release pipeline state. Written only by the publish job.
   */
  publish?: {
    /**
     * Incremented on every publish request; older requests are superseded
     */
    requestSeq?: number | null;
    lockedUntil?: string | null;
    lockedBy?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases".
 */
export interface Release {
  id: number;
  tenant?: (number | null) | Tenant;
  site: number | Site;
  version: string;
  /**
   * Opaque reference from the release pipeline adapter
   */
  artifactRef?: string | null;
  status?: ('built' | 'live' | 'superseded' | 'rolled-back' | 'failed') | null;
  templateVersion?: string | null;
  /**
   * The publish request this release answers
   */
  requestSeq?: number | null;
  /**
   * user:<id>, agent:<key> or job
   */
  publishedBy?: string | null;
  /**
   * sha256 of the canonical snapshot
   */
  checksum?: string | null;
  pageCount?: number | null;
  /**
   * Lock to verified, in milliseconds
   */
  durationMs?: number | null;
  verifiedAt?: string | null;
  error?: string | null;
  /**
   * Everything the renderer needs: site settings, published pages, confirmed facts
   */
  snapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * "home" is the start page
   */
  slug: string;
  site: number | Site;
  /**
   * Menu label (defaults to the title)
   */
  navLabel?: string | null;
  navOrder?: number | null;
  showInNav?: boolean | null;
  /**
   * Legal and practical pages
   */
  showInFooter?: boolean | null;
  blocks?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            image?: (number | null) | Media;
            /**
             * Image URL (https)
             */
            imageUrl?: string | null;
            /**
             * Alternative text for screen readers
             */
            imageAlt?: string | null;
            ctaLabel?: string | null;
            /**
             * A page slug (e.g. contact), a full URL, tel: or mailto:
             */
            ctaHref?: string | null;
            /**
             * Stars above the headline. Read from the fact base, never typed here.
             */
            rating?: ('none' | 'classification') | null;
            /**
             * Arrival, departure and guests fields that open the site’s Book link with those dates. No availability or prices: the platform runs no booking logic.
             */
            bookingBar?: boolean | null;
            /**
             * Who last shaped this content. Regeneration never overwrites human edits.
             */
            provenance?: {
              origin?: ('generated' | 'human' | 'locked') | null;
              /**
               * Fact-base reference for generated content
               */
              sourceFact?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Who last shaped this content. Regeneration never overwrites human edits.
             */
            provenance?: {
              origin?: ('generated' | 'human' | 'locked') | null;
              /**
               * Fact-base reference for generated content
               */
              sourceFact?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            /**
             * Blank lines separate paragraphs
             */
            body?: string | null;
            /**
             * Image URL (https)
             */
            imageUrl?: string | null;
            /**
             * Alternative text for screen readers
             */
            imageAlt?: string | null;
            imagePosition?: ('left' | 'right') | null;
            /**
             * Optional checklist under the text
             */
            points?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            linkLabel?: string | null;
            /**
             * A page slug (e.g. contact), a full URL, tel: or mailto:
             */
            linkHref?: string | null;
            /**
             * Who last shaped this content. Regeneration never overwrites human edits.
             */
            provenance?: {
              origin?: ('generated' | 'human' | 'locked') | null;
              /**
               * Fact-base reference for generated content
               */
              sourceFact?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'textImage';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            items?:
              | {
                  /**
                   * Optional line icon (built-in set)
                   */
                  icon?:
                    | (
                        | 'clock'
                        | 'phone'
                        | 'coffee'
                        | 'tablet'
                        | 'wifi'
                        | 'paw'
                        | 'bed'
                        | 'user'
                        | 'key'
                        | 'car'
                        | 'lift'
                        | 'leaf'
                        | 'star'
                        | 'pin'
                        | 'sun'
                        | 'shield'
                        | 'sparkle'
                        | 'utensils'
                        | 'bath'
                        | 'snowflake'
                      )
                    | null;
                  title: string;
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Who last shaped this content. Regeneration never overwrites human edits.
             */
            provenance?: {
              origin?: ('generated' | 'human' | 'locked') | null;
              /**
               * Fact-base reference for generated content
               */
              sourceFact?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | BannersBlock
        | MediaBandBlock
        | {
            heading?: string | null;
            images?:
              | {
                  url: string;
                  alt?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            text: string;
            author?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            heading?: string | null;
            text?: string | null;
            buttonLabel?: string | null;
            /**
             * A page slug (e.g. contact), a full URL, tel: or mailto:
             */
            buttonHref?: string | null;
            /**
             * Image URL (https)
             */
            imageUrl?: string | null;
            /**
             * Alternative text for screen readers
             */
            imageAlt?: string | null;
            /**
             * Who last shaped this content. Regeneration never overwrites human edits.
             */
            provenance?: {
              origin?: ('generated' | 'human' | 'locked') | null;
              /**
               * Fact-base reference for generated content
               */
              sourceFact?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            /**
             * Blank lines separate paragraphs; a line starting with "## " is a subheading
             */
            body: string;
            /**
             * Who last shaped this content. Regeneration never overwrites human edits.
             */
            provenance?: {
              origin?: ('generated' | 'human' | 'locked') | null;
              /**
               * Fact-base reference for generated content
               */
              sourceFact?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Who last shaped this content. Regeneration never overwrites human edits.
             */
            provenance?: {
              origin?: ('generated' | 'human' | 'locked') | null;
              /**
               * Fact-base reference for generated content
               */
              sourceFact?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | FormBlock
        | {
            heading?: string | null;
            /**
             * Phones, email, address and times come from confirmed facts
             */
            intro?: string | null;
            /**
             * Who last shaped this content. Regeneration never overwrites human edits.
             */
            provenance?: {
              origin?: ('generated' | 'human' | 'locked') | null;
              /**
               * Fact-base reference for generated content
               */
              sourceFact?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            heading?: string | null;
            text?: string | null;
            /**
             * Position comes from the confirmed facts geo.lat and geo.lon
             */
            zoom?: number | null;
            /**
             * Who last shaped this content. Regeneration never overwrites human edits.
             */
            provenance?: {
              origin?: ('generated' | 'human' | 'locked') | null;
              /**
               * Fact-base reference for generated content
               */
              sourceFact?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'map';
          }
        | RoomsBlock
        | OffersBlock
        | PoliciesBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * JPEG, PNG or WebP. Large phone photos are shrunk automatically before upload (max 5 MB after shrinking).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * What the photo shows, for screen readers and search engines
   */
  alt: string;
  /**
   * Photos imported from OTA listings may be licensed to the OTA or photographer.
   */
  rights?: ('owned' | 'licensed' | 'unknown') | null;
  /**
   * Where an imported photo came from
   */
  sourceUrl?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannersBlock".
 */
export interface BannersBlock {
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        /**
         * Image URL (https or /media/…)
         */
        imageUrl: string;
        imageAlt?: string | null;
        title: string;
        /**
         * A page slug, a URL, tel: or mailto: (optional)
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Who last shaped this content. Regeneration never overwrites human edits.
   */
  provenance?: {
    origin?: ('generated' | 'human' | 'locked') | null;
    /**
     * Fact-base reference for generated content
     */
    sourceFact?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banners';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBandBlock".
 */
export interface MediaBandBlock {
  /**
   * Image URL (https or /media/…)
   */
  imageUrl: string;
  /**
   * What the photo shows
   */
  imageAlt: string;
  /**
   * Who last shaped this content. Regeneration never overwrites human edits.
   */
  provenance?: {
    origin?: ('generated' | 'human' | 'locked') | null;
    /**
     * Fact-base reference for generated content
     */
    sourceFact?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  heading?: string | null;
  intro?: string | null;
  /**
   * Built under Website → Forms
   */
  form: number | Form;
  id?: string | null;
  blockName?: string | null;
  blockType: 'form';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoomsBlock".
 */
export interface RoomsBlock {
  heading?: string | null;
  intro?: string | null;
  limit?: number | null;
  /**
   * Optional "See all rooms" link beside the title
   */
  linkLabel?: string | null;
  /**
   * A page slug (e.g. rooms) or a URL
   */
  linkHref?: string | null;
  layout?: ('cards' | 'detailed') | null;
  /**
   * Who last shaped this content. Regeneration never overwrites human edits.
   */
  provenance?: {
    origin?: ('generated' | 'human' | 'locked') | null;
    sourceFact?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'rooms';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OffersBlock".
 */
export interface OffersBlock {
  heading?: string | null;
  intro?: string | null;
  limit?: number | null;
  /**
   * Who last shaped this content. Regeneration never overwrites human edits.
   */
  provenance?: {
    origin?: ('generated' | 'human' | 'locked') | null;
    sourceFact?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'offers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PoliciesBlock".
 */
export interface PoliciesBlock {
  heading?: string | null;
  /**
   * Show check-in and check-out times from the fact base
   */
  showTimes?: boolean | null;
  items?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Who last shaped this content. Regeneration never overwrites human edits.
   */
  provenance?: {
    origin?: ('generated' | 'human' | 'locked') | null;
    sourceFact?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'policies';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains".
 */
export interface Domain {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * The hotel adds a CNAME for this name at its DNS provider, pointing at the platform
   */
  hostname: string;
  site: number | Site;
  primary?: boolean | null;
  /**
   * Set by the platform team once the DNS points here. Only verified or active domains are served
   */
  status?: ('pending' | 'verified' | 'active' | 'error') | null;
  certificate?: ('none' | 'requested' | 'issued' | 'expiring' | 'error') | null;
  /**
   * Set by the release pipeline adapter, never by the app
   */
  provider?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The fact base. Confirm or reject each fact; only confirmed facts feed generation and releases.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facts".
 */
export interface Fact {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Dotted key, e.g. policy.checkout, contact.phone
   */
  key: string;
  /**
   * Normalised value
   */
  value: string;
  site?: (number | null) | Site;
  status: 'unconfirmed' | 'confirmed' | 'rejected';
  /**
   * Extraction confidence, 0 to 1
   */
  confidence?: number | null;
  method?: ('structured-data' | 'meta' | 'link' | 'text' | 'keyword' | 'heading' | 'pms' | 'manual' | 'agent') | null;
  /**
   * First URL or system the fact was found in
   */
  source?: string | null;
  occurrences?: number | null;
  /**
   * Every raw sighting: [{ source, method, raw }]
   */
  evidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Why it was confirmed or rejected, and by whom if not a platform user
   */
  decisionNote?: string | null;
  decidedBy?: (number | null) | User;
  decidedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Imports from the hotel’s current website. Start one from the site’s Website panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crawls".
 */
export interface Crawl {
  id: number;
  tenant?: (number | null) | Tenant;
  site: number | Site;
  startUrl: string;
  status: 'queued' | 'running' | 'done' | 'failed';
  maxPages?: number | null;
  pagesCrawled?: number | null;
  pagesLeft?: number | null;
  /**
   * Distinct facts written to the fact base (new or refreshed)
   */
  factsFound?: number | null;
  factsNew?: number | null;
  /**
   * Whether a model proposed extra facts, and how many
   */
  aiPass?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Site audit: pages, titles, structured data, thin pages
   */
  audit?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  log?: string | null;
  startedBy?: string | null;
  finishedAt?: string | null;
  state?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * What the platform noticed about your website, with a fix to approve when there is one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues".
 */
export interface Issue {
  id: number;
  tenant?: (number | null) | Tenant;
  site: number | Site;
  kind:
    | 'broken-link'
    | 'missing-alt'
    | 'missing-meta'
    | 'stale-content'
    | 'expired-offer'
    | 'missing-fact'
    | 'uptime'
    | 'performance'
    | 'accessibility'
    | 'unanswered';
  severity: 'info' | 'warning' | 'error';
  title: string;
  detail?: string | null;
  /**
   * Where it was seen
   */
  url?: string | null;
  status: 'open' | 'applied' | 'resolved' | 'dismissed';
  fingerprint: string;
  /**
   * What "Apply" would do
   */
  fixLabel?: string | null;
  fix?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  source?: string | null;
  detectedAt?: string | null;
  resolvedAt?: string | null;
  appliedBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every change to your website content, with who made it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  tenant?: (number | null) | Tenant;
  collectionSlug: string;
  docId: string;
  operation: 'create' | 'update' | 'delete';
  /**
   * user:<id> <email>, api-key:<id>, job, system
   */
  actor: string;
  summary: string;
  /**
   * Field names that changed
   */
  changed?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * generation, translation, import, publish…
   */
  context?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Room types shown on the hotel website. Changes go live with the next publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  /**
   * e.g. Superior, Comfort
   */
  category?: string | null;
  order?: number | null;
  /**
   * One or two sentences for the room card
   */
  summary?: string | null;
  description?: string | null;
  sizeSqm?: number | null;
  maxOccupancy?: number | null;
  /**
   * e.g. Double bed or two singles
   */
  bed?: string | null;
  view?: string | null;
  features?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        url: string;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Packages and promotions shown on the website between their dates. Changes go live with the next publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  active?: boolean | null;
  order?: number | null;
  /**
   * Short badge, e.g. "-10 %" or "Breakfast included"
   */
  highlight?: string | null;
  summary: string;
  /**
   * Small print shown under the offer
   */
  conditions?: string | null;
  validFrom?: string | null;
  validTo?: string | null;
  imageUrl?: string | null;
  imageAlt?: string | null;
  ctaLabel?: string | null;
  /**
   * A page slug (e.g. contact), a URL, tel: or mailto:
   */
  ctaHref?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  tenant?: (number | null) | Tenant;
  site: number | Site;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  tenant?: (number | null) | Tenant;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
  };
  sites?: {
    /**
     * Allow clients to find sites.
     */
    find?: boolean | null;
    /**
     * Allow clients to update sites.
     */
    update?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
  };
  rooms?: {
    /**
     * Allow clients to find rooms.
     */
    find?: boolean | null;
    /**
     * Allow clients to create rooms.
     */
    create?: boolean | null;
    /**
     * Allow clients to update rooms.
     */
    update?: boolean | null;
  };
  facts?: {
    /**
     * Allow clients to find facts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create facts.
     */
    create?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  hasAPIKey?: boolean | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'touchPageSeo' | 'publishSite';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'touchPageSeo' | 'publishSite') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'domains';
        value: number | Domain;
      } | null)
    | ({
        relationTo: 'releases';
        value: number | Release;
      } | null)
    | ({
        relationTo: 'facts';
        value: number | Fact;
      } | null)
    | ({
        relationTo: 'crawls';
        value: number | Crawl;
      } | null)
    | ({
        relationTo: 'issues';
        value: number | Issue;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'rooms';
        value: number | Room;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  plan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  tenant?: T;
  brandProposal?: T;
  name?: T;
  slug?: T;
  sourceUrl?: T;
  brandName?: T;
  timezone?: T;
  enabledLocales?: T;
  defaultLocale?: T;
  theme?: T;
  template?: T;
  designChannel?: T;
  brand?:
    | T
    | {
        accent?: T;
        background?: T;
        text?: T;
        headingFont?: T;
        bodyFont?: T;
        corners?: T;
      };
  status?: T;
  tagline?: T;
  logoUrl?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  currentRelease?: T;
  publish?:
    | T
    | {
        requestSeq?: T;
        lockedUntil?: T;
        lockedBy?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  site?: T;
  navLabel?: T;
  navOrder?: T;
  showInNav?: T;
  showInFooter?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              imageUrl?: T;
              imageAlt?: T;
              ctaLabel?: T;
              ctaHref?: T;
              rating?: T;
              bookingBar?: T;
              provenance?:
                | T
                | {
                    origin?: T;
                    sourceFact?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              provenance?:
                | T
                | {
                    origin?: T;
                    sourceFact?: T;
                  };
              id?: T;
              blockName?: T;
            };
        textImage?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              imageUrl?: T;
              imageAlt?: T;
              imagePosition?: T;
              points?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              linkLabel?: T;
              linkHref?: T;
              provenance?:
                | T
                | {
                    origin?: T;
                    sourceFact?: T;
                  };
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              provenance?:
                | T
                | {
                    origin?: T;
                    sourceFact?: T;
                  };
              id?: T;
              blockName?: T;
            };
        banners?: T | BannersBlockSelect<T>;
        mediaBand?: T | MediaBandBlockSelect<T>;
        gallery?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    url?: T;
                    alt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              author?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              text?: T;
              buttonLabel?: T;
              buttonHref?: T;
              imageUrl?: T;
              imageAlt?: T;
              provenance?:
                | T
                | {
                    origin?: T;
                    sourceFact?: T;
                  };
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              heading?: T;
              body?: T;
              provenance?:
                | T
                | {
                    origin?: T;
                    sourceFact?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              provenance?:
                | T
                | {
                    origin?: T;
                    sourceFact?: T;
                  };
              id?: T;
              blockName?: T;
            };
        form?: T | FormBlockSelect<T>;
        contact?:
          | T
          | {
              heading?: T;
              intro?: T;
              provenance?:
                | T
                | {
                    origin?: T;
                    sourceFact?: T;
                  };
              id?: T;
              blockName?: T;
            };
        map?:
          | T
          | {
              heading?: T;
              text?: T;
              zoom?: T;
              provenance?:
                | T
                | {
                    origin?: T;
                    sourceFact?: T;
                  };
              id?: T;
              blockName?: T;
            };
        rooms?: T | RoomsBlockSelect<T>;
        offers?: T | OffersBlockSelect<T>;
        policies?: T | PoliciesBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannersBlock_select".
 */
export interface BannersBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        imageUrl?: T;
        imageAlt?: T;
        title?: T;
        href?: T;
        id?: T;
      };
  provenance?:
    | T
    | {
        origin?: T;
        sourceFact?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBandBlock_select".
 */
export interface MediaBandBlockSelect<T extends boolean = true> {
  imageUrl?: T;
  imageAlt?: T;
  provenance?:
    | T
    | {
        origin?: T;
        sourceFact?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  form?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoomsBlock_select".
 */
export interface RoomsBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  limit?: T;
  linkLabel?: T;
  linkHref?: T;
  layout?: T;
  provenance?:
    | T
    | {
        origin?: T;
        sourceFact?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OffersBlock_select".
 */
export interface OffersBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  limit?: T;
  provenance?:
    | T
    | {
        origin?: T;
        sourceFact?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PoliciesBlock_select".
 */
export interface PoliciesBlockSelect<T extends boolean = true> {
  heading?: T;
  showTimes?: T;
  items?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  provenance?:
    | T
    | {
        origin?: T;
        sourceFact?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  rights?: T;
  sourceUrl?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains_select".
 */
export interface DomainsSelect<T extends boolean = true> {
  tenant?: T;
  hostname?: T;
  site?: T;
  primary?: T;
  status?: T;
  certificate?: T;
  provider?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases_select".
 */
export interface ReleasesSelect<T extends boolean = true> {
  tenant?: T;
  site?: T;
  version?: T;
  artifactRef?: T;
  status?: T;
  templateVersion?: T;
  requestSeq?: T;
  publishedBy?: T;
  checksum?: T;
  pageCount?: T;
  durationMs?: T;
  verifiedAt?: T;
  error?: T;
  snapshot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facts_select".
 */
export interface FactsSelect<T extends boolean = true> {
  tenant?: T;
  key?: T;
  value?: T;
  site?: T;
  status?: T;
  confidence?: T;
  method?: T;
  source?: T;
  occurrences?: T;
  evidence?: T;
  decisionNote?: T;
  decidedBy?: T;
  decidedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crawls_select".
 */
export interface CrawlsSelect<T extends boolean = true> {
  tenant?: T;
  site?: T;
  startUrl?: T;
  status?: T;
  maxPages?: T;
  pagesCrawled?: T;
  pagesLeft?: T;
  factsFound?: T;
  factsNew?: T;
  aiPass?: T;
  audit?: T;
  log?: T;
  startedBy?: T;
  finishedAt?: T;
  state?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues_select".
 */
export interface IssuesSelect<T extends boolean = true> {
  tenant?: T;
  site?: T;
  kind?: T;
  severity?: T;
  title?: T;
  detail?: T;
  url?: T;
  status?: T;
  fingerprint?: T;
  fixLabel?: T;
  fix?: T;
  source?: T;
  detectedAt?: T;
  resolvedAt?: T;
  appliedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  tenant?: T;
  collectionSlug?: T;
  docId?: T;
  operation?: T;
  actor?: T;
  summary?: T;
  changed?: T;
  context?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  category?: T;
  order?: T;
  summary?: T;
  description?: T;
  sizeSqm?: T;
  maxOccupancy?: T;
  bed?: T;
  view?: T;
  features?:
    | T
    | {
        label?: T;
        id?: T;
      };
  images?:
    | T
    | {
        url?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  active?: T;
  order?: T;
  highlight?: T;
  summary?: T;
  conditions?: T;
  validFrom?: T;
  validTo?: T;
  imageUrl?: T;
  imageAlt?: T;
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  tenant?: T;
  site?: T;
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  tenant?: T;
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  sites?:
    | T
    | {
        find?: T;
        update?: T;
      };
  media?:
    | T
    | {
        find?: T;
      };
  rooms?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  facts?:
    | T
    | {
        find?: T;
        create?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  hasAPIKey?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskTouchPageSeo".
 */
export interface TaskTouchPageSeo {
  input: {
    tenantId: number;
    pageId: number;
    description: string;
  };
  output: {
    updated?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPublishSite".
 */
export interface TaskPublishSite {
  input: {
    tenantId: number;
    siteId: number;
    seq: number;
    by?: string | null;
  };
  output: {
    outcome?: string | null;
    version?: string | null;
    durationMs?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}