import type { PageInput } from '../types'

/**
 * Legal pages for customer zero. Company details come from the hotel's current legal notice
 * (www.hotel-herse-dor.com/mentions-legales, fetched 24 Sep 2026). DRAFTS for the owner to
 * validate before the site replaces the old one; they are not legal advice.
 */
const DRAFT_NOTE = {
  fr: 'Version de travail à valider par l’exploitant.',
  en: 'Working draft, to be validated by the hotel.',
}

export const legalNotice: PageInput = {
  slug: 'mentions-legales',
  navOrder: 90,
  showInNav: false,
  showInFooter: true,
  title: { fr: 'Mentions légales', en: 'Legal notice' },
  seo: { description: { fr: 'Mentions légales du site de l’Hôtel de la Herse d’Or.', en: 'Legal notice for the Hôtel de la Herse d’Or website.' } },
  blocks: [
    {
      blockType: 'text',
      heading: { fr: 'Mentions légales', en: 'Legal notice' },
      body: {
        fr: [
          '## Éditeur du site',
          'Hôtel de la Herse d’Or, SAS au capital de 38 112,25 €',
          '20 rue Saint-Antoine, 75004 Paris, France',
          'SIRET 632 035 911 00015 · RCS Paris B 632 035 911 · TVA intracommunautaire FR51632035911',
          'Directeur de la publication : M. Kamel Soussi',
          'Contact : info@hotel-herse-dor.com · +33 1 48 87 84 09',
          '## Hébergement',
          'Le site est servi par la plateforme Hotelier Website Platform (xedge), hébergée sur Tencent Cloud EdgeOne (région Francfort, Allemagne). Les données du site sont stockées chez Neon (région Francfort, Allemagne).',
          '## Propriété intellectuelle',
          'Les textes et photographies de ce site appartiennent à l’Hôtel de la Herse d’Or, sauf mention contraire. Toute reproduction sans autorisation écrite est interdite.',
          '## Réservations',
          'Ce site présente l’hôtel. Les réservations se font directement auprès de la réception, par téléphone ou par e-mail.',
          DRAFT_NOTE.fr,
        ].join('\n\n'),
        en: [
          '## Publisher',
          'Hôtel de la Herse d’Or, a French SAS with share capital of €38,112.25',
          '20 rue Saint-Antoine, 75004 Paris, France',
          'SIRET 632 035 911 00015 · RCS Paris B 632 035 911 · EU VAT FR51632035911',
          'Publication director: Mr Kamel Soussi',
          'Contact: info@hotel-herse-dor.com · +33 1 48 87 84 09',
          '## Hosting',
          'The site is served by the Hotelier Website Platform (xedge), hosted on Tencent Cloud EdgeOne (Frankfurt region, Germany). Site data is stored with Neon (Frankfurt region, Germany).',
          '## Intellectual property',
          'Texts and photographs on this site belong to Hôtel de la Herse d’Or unless stated otherwise. Reproduction without written permission is prohibited.',
          '## Bookings',
          'This site presents the hotel. Bookings are made directly with reception, by phone or email.',
          DRAFT_NOTE.en,
        ].join('\n\n'),
      },
    },
  ],
}

export const privacy: PageInput = {
  slug: 'confidentialite',
  navOrder: 91,
  showInNav: false,
  showInFooter: true,
  title: { fr: 'Confidentialité & cookies', en: 'Privacy & cookies' },
  seo: { description: { fr: 'Politique de confidentialité et cookies de l’Hôtel de la Herse d’Or.', en: 'Privacy and cookie policy of Hôtel de la Herse d’Or.' } },
  blocks: [
    {
      blockType: 'text',
      heading: { fr: 'Confidentialité & cookies', en: 'Privacy & cookies' },
      body: {
        fr: [
          '## Responsable du traitement',
          'Hôtel de la Herse d’Or, 20 rue Saint-Antoine, 75004 Paris · info@hotel-herse-dor.com',
          '## Aucun cookie, aucun traceur',
          'Ce site ne dépose aucun cookie et n’utilise aucun outil de mesure d’audience ni de publicité. Aucun bandeau de consentement n’est donc nécessaire.',
          '## Carte',
          'La page Contact affiche une carte OpenStreetMap. Lorsque vous la consultez, votre navigateur contacte les serveurs d’OpenStreetMap, qui reçoivent votre adresse IP selon leur propre politique de confidentialité.',
          '## Données que vous nous transmettez',
          'Si vous nous écrivez ou nous appelez, nous utilisons vos coordonnées uniquement pour vous répondre et préparer votre séjour. Elles ne sont ni vendues ni cédées.',
          '## Journaux techniques',
          'Comme tout site web, l’hébergeur conserve brièvement des journaux techniques (adresse IP, page demandée) pour la sécurité et le bon fonctionnement du service.',
          '## Vos droits',
          'Vous pouvez demander l’accès, la rectification ou l’effacement de vos données en écrivant à info@hotel-herse-dor.com. Vous pouvez aussi saisir la CNIL (www.cnil.fr).',
          DRAFT_NOTE.fr,
        ].join('\n\n'),
        en: [
          '## Controller',
          'Hôtel de la Herse d’Or, 20 rue Saint-Antoine, 75004 Paris · info@hotel-herse-dor.com',
          '## No cookies, no trackers',
          'This site sets no cookies and uses no analytics or advertising tools, so no consent banner is needed.',
          '## Map',
          'The Contact page shows an OpenStreetMap map. When you view it, your browser contacts OpenStreetMap’s servers, which receive your IP address under their own privacy policy.',
          '## Information you send us',
          'If you write to or call us, we use your details only to reply and prepare your stay. They are never sold or passed on.',
          '## Technical logs',
          'Like any website, the host briefly keeps technical logs (IP address, page requested) for security and reliable service.',
          '## Your rights',
          'You can ask to access, correct or erase your data by writing to info@hotel-herse-dor.com. You can also contact the French data protection authority, CNIL (www.cnil.fr).',
          DRAFT_NOTE.en,
        ].join('\n\n'),
      },
    },
  ],
}

export const accessibility: PageInput = {
  slug: 'accessibilite',
  navOrder: 92,
  showInNav: false,
  showInFooter: true,
  title: { fr: 'Accessibilité', en: 'Accessibility' },
  seo: { description: { fr: 'Déclaration d’accessibilité du site de l’Hôtel de la Herse d’Or.', en: 'Accessibility statement for the Hôtel de la Herse d’Or website.' } },
  blocks: [
    {
      blockType: 'text',
      heading: { fr: 'Déclaration d’accessibilité', en: 'Accessibility statement' },
      body: {
        fr: [
          '## Notre engagement',
          'Nous voulons que ce site soit utilisable par tous. Il vise le niveau AA des règles WCAG 2.2.',
          '## État de conformité',
          'Le site n’a pas encore fait l’objet d’un audit complet. En attendant, il est conçu avec une structure de titres claire, des textes alternatifs sur les images, une navigation au clavier et des contrastes suffisants.',
          '## À l’hôtel',
          'L’hôtel dispose d’un ascenseur accessible aux personnes à mobilité réduite. N’hésitez pas à nous préciser vos besoins avant votre arrivée.',
          '## Nous signaler un problème',
          'Si un contenu vous est inaccessible, écrivez à info@hotel-herse-dor.com ou appelez le +33 1 48 87 84 09 : nous vous transmettrons l’information sous une autre forme.',
          DRAFT_NOTE.fr,
        ].join('\n\n'),
        en: [
          '## Our commitment',
          'We want this site to work for everyone. It aims for WCAG 2.2 level AA.',
          '## Compliance status',
          'The site has not had a full audit yet. Meanwhile it is built with a clear heading structure, text alternatives on images, keyboard navigation and sufficient contrast.',
          '## At the hotel',
          'The hotel has a lift accessible to guests with reduced mobility. Please tell us about your needs before you arrive.',
          '## Report a problem',
          'If any content is not accessible to you, email info@hotel-herse-dor.com or call +33 1 48 87 84 09 and we will provide the information another way.',
          DRAFT_NOTE.en,
        ].join('\n\n'),
      },
    },
  ],
}

/**
 * House rules and terms of sale, rewritten from the hotel's current page
 * (www.hotel-herse-dor.com/reglement-interieur-et-conditions-generales-de-vente, fetched 25 Sep
 * 2026): every amount, time and rule is the hotel's own. Draft for the owner (and a lawyer).
 */
export const houseRulesAndTerms: PageInput = {
  slug: 'reglement-cgv',
  navOrder: 93,
  showInNav: false,
  showInFooter: true,
  title: { fr: 'Règlement intérieur et conditions générales de vente', en: 'House rules and terms of sale' },
  navLabel: { fr: 'Règlement & CGV', en: 'House rules & terms' },
  seo: { description: { fr: 'Règlement intérieur et conditions générales de vente de l’Hôtel de la Herse d’Or, Paris.', en: 'House rules and terms of sale of Hôtel de la Herse d’Or, Paris.' } },
  blocks: [
    {
      blockType: 'text',
      heading: { fr: 'Règlement intérieur', en: 'House rules' },
      body: {
        fr: [
          '## 1. Accès à l’établissement',
          'L’hôtel peut refuser l’accès à toute personne dont la tenue est indécente ou négligée, ou dont le comportement est bruyant, incorrect ou alcoolisé. Une pièce d’identité est demandée à l’arrivée.',
          '## 2. Horaires',
          'L’hôtel est ouvert 24h/24, 365 jours par an.',
          '## 3. Occupation des chambres',
          'Les visiteurs non enregistrés ne sont pas admis dans les chambres sans accord préalable de la réception. Le nombre d’occupants ne peut dépasser la capacité de la chambre.',
          '## 4. Arrivée et départ',
          'Les chambres sont disponibles à partir de 15h30 et doivent être libérées avant 11h00 le jour du départ. Un accès anticipé n’est pas garanti sans accord préalable.',
          '## 5. Clés',
          'Les clés doivent être restituées au départ. En cas de non-restitution, une pénalité de 100 € est prélevée sur la carte bancaire.',
          '## 6. Tranquillité',
          'Le bruit est interdit, y compris en journée ; le calme est obligatoire entre 22h00 et 8h00. Le non-respect de cette règle entraîne le départ immédiat, sans remboursement.',
          '## 7. Responsabilités',
          'Les enfants et les animaux acceptés restent sous la responsabilité du client. Tout dommage est facturé au client.',
          '## 8. Interdictions',
          'Il est interdit de fumer dans l’hôtel : pénalité de 90 €, des poursuites étant possibles. Le déclenchement intempestif de l’alarme incendie est facturé 150 €. Toute cuisine en chambre est strictement interdite.',
          '## 9. Vidéosurveillance',
          'Des caméras sont installées dans les parties communes.',
          '## 10. Acceptation',
          'Toute violation du règlement entraîne l’annulation immédiate du séjour, sans indemnité.',
          DRAFT_NOTE.fr,
        ].join('\n\n'),
        en: [
          '## 1. Access',
          'The hotel may refuse access to anyone whose dress is indecent or unkempt, or whose behaviour is noisy, improper or intoxicated. Identification is required at check-in.',
          '## 2. Opening hours',
          'The hotel is open 24 hours a day, 365 days a year.',
          '## 3. Room occupancy',
          'Unregistered visitors are not admitted to the rooms without prior agreement from reception. The number of occupants may not exceed the room’s capacity.',
          '## 4. Arrival and departure',
          'Rooms are available from 3:30 pm and must be vacated by 11:00 am on the day of departure. Early access is not guaranteed without prior agreement.',
          '## 5. Keys',
          'Keys must be returned on departure. If a key is not returned, a €100 penalty is charged to the bank card.',
          '## 6. Quiet',
          'Noise is not allowed, including during the day; quiet is required between 10:00 pm and 8:00 am. Breaking this rule leads to immediate departure without refund.',
          '## 7. Responsibility',
          'Children and accepted pets remain the guest’s responsibility. Any damage is charged to the guest.',
          '## 8. Prohibitions',
          'Smoking is prohibited in the hotel: €90 penalty, and legal action is possible. Setting off the fire alarm without cause is charged €150. Cooking in the rooms is strictly prohibited.',
          '## 9. Video surveillance',
          'Cameras are installed in the common areas.',
          '## 10. Acceptance',
          'Any breach of these rules leads to immediate cancellation of the stay, without compensation.',
          DRAFT_NOTE.en,
        ].join('\n\n'),
      },
    },
    {
      blockType: 'text',
      heading: { fr: 'Conditions générales de vente', en: 'Terms of sale' },
      body: {
        fr: [
          '## I. Établissement',
          'Hôtel de la Herse d’Or · SIRET 632 035 911 00015 · 20, rue Saint-Antoine, 75004 Paris · +33 1 48 87 84 09.',
          '## II. Réservation et annulation',
          'La réservation doit être réglée intégralement au moment de la commande. Les réservations sont non remboursables : aucun remboursement n’est effectué. En cas de non-présentation, la totalité de la réservation est facturée. Un départ tardif peut entraîner des frais allant jusqu’à 100 % du prix de la chambre réservée. Seules les personnes majeures peuvent réserver ; les mineurs doivent être accompagnés d’un adulte. Le client supporte le coût de remise en état en cas de dégradation.',
          '## III. Tarifs et paiement',
          'Les tarifs s’entendent TVA comprise, par chambre et pour le nombre de personnes indiqué. Ils peuvent être modifiés sans préavis ; les tarifs confirmés restent contractuels. La taxe de séjour est due par les clients de plus de 18 ans et varie selon la période. Les petits animaux sont acceptés moyennant 20 € par jour. Le petit-déjeuner est en supplément.',
          '## IV. Assurances',
          'L’hôtel décline toute responsabilité en cas de force majeure.',
          '## V. Réclamations',
          'Toute réclamation doit être adressée par lettre recommandée dans un délai de 8 jours. Les bagages non récupérés sous 24 heures sont facturés.',
          '## VI. Recours du consommateur',
          'Démarchage téléphonique : le client peut s’inscrire sur la liste d’opposition Bloctel (www.bloctel.gouv.fr). Médiation : Médiation Tourisme et Voyage, www.mtv.travel, 01 87 44 77 90.',
          '## VII. Droit de rétractation',
          'Le droit de rétractation ne s’applique pas aux prestations d’hébergement.',
          '## VIII. Plateforme européenne de règlement des litiges',
          'https://ec.europa.eu/consumers/odr/',
          '## IX. Droit applicable',
          'Le droit français s’applique ; les tribunaux de Paris sont compétents.',
          DRAFT_NOTE.fr,
        ].join('\n\n'),
        en: [
          '## I. The establishment',
          'Hôtel de la Herse d’Or · SIRET 632 035 911 00015 · 20, rue Saint-Antoine, 75004 Paris · +33 1 48 87 84 09.',
          '## II. Booking and cancellation',
          'The booking must be paid in full when it is made. Bookings are non-refundable: no refund is given. In case of no-show, the whole booking is charged. A late departure may incur fees of up to 100 % of the price of the room booked. Only adults may book; minors must be accompanied by an adult. The guest bears the cost of repairs in case of damage.',
          '## III. Rates and payment',
          'Rates include VAT, per room and for the number of guests stated. They may change without notice; confirmed rates remain contractual. The tourist tax is due by guests over 18 and varies with the season. Small pets are accepted for €20 per day. Breakfast is extra.',
          '## IV. Insurance',
          'The hotel accepts no liability in case of force majeure.',
          '## V. Complaints',
          'Complaints must be sent by registered letter within 8 days. Luggage not collected within 24 hours is charged.',
          '## VI. Consumer remedies',
          'Telephone canvassing: guests may register on the Bloctel opposition list (www.bloctel.gouv.fr). Mediation: Médiation Tourisme et Voyage, www.mtv.travel, +33 1 87 44 77 90.',
          '## VII. Right of withdrawal',
          'The right of withdrawal does not apply to accommodation services.',
          '## VIII. European dispute-resolution platform',
          'https://ec.europa.eu/consumers/odr/',
          '## IX. Applicable law',
          'French law applies; the courts of Paris have jurisdiction.',
          DRAFT_NOTE.en,
        ].join('\n\n'),
      },
    },
  ],
}

